---
# tasks file for senchacmd
- name: Check if sencha cmd is installed.
  shell: "{{ senchacmd_install_dir }}/{{ senchacmd_version }}/sencha"
  register: sencha_result
  failed_when: false
  changed_when: false

- set_fact:
    sencha_installed: "{{ sencha_result.rc == 0 }}"

- name: install sencha-cmd
  include_tasks: install.yml
  when: sencha_installed != true

- name: Set repo directory permission
  file:
    path: "{{ senchacmd_install_dir }}/repo"
    state: directory
    mode: 0777